version: "3.1"

services:
  node-app:
    build: .
    image: node-app
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/node-app
    networks:
      - node-network
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/db
    networks:
      - node-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: provi
      MONGO_INITDB_ROOT_PASSWORD: provi

volumes:
  dbdata:

networks:
  node-network:
    driver: bridge

