version: "3.1"

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: wpro
      MONGO_INITDB_ROOT_PASSWORD: wpro

volumes:
  dbdata:

